# Generated by Django 3.2.18 on 2023-05-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField()),
                ('release_date', models.DateField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('vote_average', models.FloatField(default=0)),
                ('popularity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopRatedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField()),
                ('release_date', models.DateField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('vote_average', models.FloatField(default=0)),
                ('popularity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalMovies',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_date', models.DateField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('vote_average', models.FloatField(default=0)),
                ('popularity', models.FloatField()),
                ('genres', models.CharField(blank=True, max_length=100)),
                ('youtube_key', models.CharField(max_length=500)),
                ('runtime', models.CharField(max_length=50)),
            ],
        ),
    ]
