# Generated by Django 3.2.18 on 2023-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='adult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='backdrop_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='original_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='totalmovies',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalmovies',
            name='popularity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='totalmovies',
            name='runtime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='totalmovies',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
