# Generated by Django 3.2.18 on 2023-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularmovies',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
